INSERT INTO client_version(major, minor, released) VALUES (0, 1, now());

INSERT INTO roles(role, description) VALUES ('client', 'this is a test client role');
INSERT INTO users(username, password) VALUES ('testclient', 'n3NeDfmh3ccCvwoae4MDP59xU6AMKd6CztrcmVcomwU='); -- testclient/testpassowrd hash generated by java -cp $WILDFLY_HOME/modules/system/layers/base/org/picketbox/main/picketbox-4.9.4.Final.jar org.jboss.security.Base64Encoder "testpassword" "SHA-256"
INSERT INTO user_roles(user_id, role_id) VALUES (1, 1);
